### PR TITLE
tungtran.is-a-good.dev

### PR DESCRIPTION
**Pull request by tunganhtran**
I create my profile, please help me make it online
Thank you

### CODE REVIEW

**Comment by tunganhtran** [comment]
I updated owner

**Comment by Tweak4141** [comment]
CNAME record not valid.

**Comment by tungtran-zb** [comment]
@Tweak4141 please confirm

**Comment by tunganhtran** [comment]
@Tweak4141 please confirm

**Comment by Tweak4141** [comment]
Hey there, your cnqme is still invalid. Please remove the path. @tunganhtran

**Comment by wclarkey** [comment]
> @Tweak4141 please confirm

Please dont mention maintainers. Wait patiently, we have logs that show us when a change happens. @tunganhtran

**Pull request merged**
