### PR TITLE
Create wesley.json

### PR DESCRIPTION
**Pull request by westhecool**

### CODE REVIEW

**Comment by wclarkey** [comment]
Email address is not valid. Pull request will not be merged until this is fixed.

**Comment by westhecool** [comment]
> Email address is not valid. Pull request will not be merged until this is fixed.

Wait what? You can't deliver to it? Or what?

**Comment by wclarkey** [comment]
Can this be fixed or the email be replaced with another one that is accessible

**Comment by wclarkey** [comment]
Make sure to also read the information [here](https://docs.is-a-good.dev/about#domain-limitations) *(https://docs.is-a-good.dev/about#domain-limitations)*

**Comment by westhecool** [comment]
> Can this be fixed or the email be replaced with another one that is accessible

just use noonehere@null.net

**Comment by wclarkey** [comment]
image

**Comment by westhecool** [comment]
> image

it doesn't appear to be working but it's working.
if you don't believe me, could you email me a verification code?

**Comment by wclarkey** [comment]
A verification code has been sent.

**Comment by westhecool** [comment]
> A verification code has been sent.

`9384853058`

**Pull request merged**
