### PR TITLE
Register pathjerryio.is-a-good.dev

### PR DESCRIPTION
**Pull request by jacobjuneau6**
Added `pathjerryio.is-a-good.dev` using the [CLI](https://www.npmjs.com/package/@is-a-good-dev/cli).

### CODE REVIEW

**Comment by Tweak4141** [comment]
Incorrect A value.

**Review by Tweak4141 — CHANGES_REQUESTED** [review]
Please change to an A or CNAME record. We do not support NS.

**Comment by jacobjuneau6** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Tweak4141** [comment]
That's not the issue. Your file is invalid.

**Comment by jacobjuneau6** [comment]
Where is there an NS record?

**Comment by Tweak4141** [comment]
joyce.ns.cloudflare.com

**Comment by jacobjuneau6** [comment]
Change made

**Review by Tweak4141 — APPROVED** [review]

**Pull request merged**
