### PR TITLE
Update nolimanom.json

### PR DESCRIPTION
**Pull request by nolimanom**
Sorry for frequent pull requests, just trying to undersand why it gives error everytime

### CODE REVIEW

**Comment by Tweak4141** [comment]
This won't do anything, you need to add the domain to your GitHub pages repo

**Comment by Tweak4141** [comment]
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

**Comment by nolimanom** [comment]
> This won't do anything, you need to add the domain to your GitHub pages repo

fixed this

**Comment by nolimanom** [comment]
> This won't do anything, you need to add the domain to your GitHub pages repo

oh, sorry...

**Pull request closed without merging**
