### PR TITLE
bowen pull request

### PR DESCRIPTION
**Pull request by donottakemyusername**

### CODE REVIEW

**Review by WilliamDavidHarrison — CHANGES_REQUESTED** [review]
I can't resolve your website, I get an error 404.

**Comment by donottakemyusername** [comment]
It's showing me an error after running a pull request and I am not sure what the problem is. Can you help me check it? Thank you!

**Comment by WilliamDavidHarrison** [comment]
> It's showing me an error after running a pull request and I am not sure what the problem is. Can you help me check it? Thank you!

That is the first greetings, don't worry about that.

**Comment by donottakemyusername** [comment]
> > It's showing me an error after running a pull request and I am not sure what the problem is. Can you help me check it? Thank you!
> 
> That is the first greetings, don't worry about that. It's an issue on our end.

Ok I see. Thank you for letting me know!

**Comment by WilliamDavidHarrison** [comment]
Also, I can't reach your website.

**Review by WilliamDavidHarrison — APPROVED** [review]

**Review by Tweak4141 — APPROVED** [review]

**Comment by Tweak4141** [comment]
Just to clarify:
You want your subdomain to be:
`bz99.is-a-good.dev`
The name field should be what you want your subdomain to be.
If you want your subdomain to be:
`bowen.is-a-good.dev`
then please change your name field to "bowen"

**Comment by donottakemyusername** [comment]
Oh please help me change it to bowen.is-a-good.dev. I think the latter is
better. Thank you!

Best,
Bowen

**Pull request merged**
