### PR TITLE
Create k42.json 🦉

### PR DESCRIPTION
**Pull request by CrystallineButterfly**
Hey there, good to meet you 🛸

Blessings to you 🦋

P.S: Please let me know if the CNAME value format is correct🙏

All the best- K 🚀

### CODE REVIEW

**Comment by Tweak4141** [comment]
Hey there, both name and value fields are invalid.

**Comment by CrystallineButterfly** [comment]
Ok thank you @Tweak4141 I have updated the file now, with an unstoppable domain I own, and the correct subdomain :)

**Comment by CrystallineButterfly** [comment]
> > Ok thank you @Tweak4141 I have updated the file now, with an unstoppable domain I own, and the correct subdomain :)
> 
> Sounds good @CrystallineButterfly . I noticed your domain is a Web3 domain. I am not quite familiar on how this works, so I'm just double checking. If added as a CNAME, are you able to generate an SSL certificate? Will this properly resolve? SSL is required for domains that end in .dev

Yeah I think it does, however, an IFPS hash may be replacing that feature, so to be sure, I can add a vercel domain instead, if that works? 
Also I am a web3 dev if you ever wanna call and/ or collab on a project :)

**Comment by CrystallineButterfly** [comment]
Awesome, So I added a vercel domain, as I aim to use the k42.is-a-good.dev for this site 🙏

**Comment by Tweak4141** [comment]
@CrystallineButterfly for future reference, CNAME records should only contain the domain, and not the protocol and trailing slash. If you need any further help with connecting your vercel domain, join our discord or mention me here.

**Pull request merged**
