### PR TITLE
Change to proxied mode

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**

### CODE REVIEW

**Comment by Tweak4141** [comment]
Could you please provide a reason on why you need Cloudflare's proxy mode on?

**Comment by WilliamDavidHarrison** [comment]
> Could you please provide a reason on why you need Cloudflare's proxy mode on?

It helps hide the IP slightly, so might as well?

**Review by wclarkey — APPROVED** [review]

**Comment by wclarkey** [comment]
Approved however, slightly confused as to the reason of needing to proxy a CNAME record.

**Comment by WilliamDavidHarrison** [comment]
> Approved however, slightly confused as to the reason of needing to proxy a CNAME record.

Hide the IP sort of and to use Cloudflares CDN.

**Comment by Tweak4141** [comment]
@WilliamDavidHarrison This had to be set manually, but it has already been proxied.
Forgot to merge.

**Comment by WilliamDavidHarrison** [comment]
Can you unproxy it?

**Comment by Tweak4141** [comment]
Mmm, just realized that the proxy would mess up your SSL certs, didn't you.

**Comment by Tweak4141** [comment]
Alright, it is unproxied.

**Comment by WilliamDavidHarrison** [comment]
> Mmm, just realized that the proxy would mess up your SSL certs, didn't you.

Well it actually doesn't (on my domains it doesn't), but I just figured it might be better without proxy for certain things.

**Pull request closed without merging**
