### PR TITLE
ak.json

### PR DESCRIPTION
**Pull request by AKGaming0001**

### CODE REVIEW

**Comment by wclarkey** [comment]
Please add an email.

**Comment by AKGaming0001** [comment]
> 

is it compulsory? can i add discord or twitter instead or just email?

**Comment by Tweak4141** [comment]
Yes, it is compulsory.

**Comment by AKGaming0001** [comment]
> Yes, it is compulsory.

ok just a moment

**Comment by AKGaming0001** [comment]
> Yes, it is compulsory.

i hope it's fine now, and thank you to you 🙂

**Pull request merged**
