### PR TITLE
Create john.json

### PR DESCRIPTION
**Pull request by Jkean2012**

### CODE REVIEW

**Review by Tweak4141 — CHANGES_REQUESTED** [review]
Please follow our file format.

**Comment by Jkean2012** [comment]
ok i Updated it to follow format

**Review by Tweak4141 — CHANGES_REQUESTED** [review]
The record-type must be of type A, AAAA, or CNAME.
name must be filled in with the subdomain you wish to claim, and must match the file name.
value must be the record value.

**Review by Tweak4141 — CHANGES_REQUESTED** [review]
This is still inavlid, record type must be changed.
Name must match file name.

**Comment by Jkean2012** [comment]
ok i think i fixed it

**Review by Tweak4141 — CHANGES_REQUESTED** [review]
record-type must be changed to A, AAAA, or CNAME.
Please see the documentation.

Additionally, we do not support netlify. Please use vercel.

**Comment by Jkean2012** [comment]
does this work now?

**Review by Tweak4141 — DISMISSED** [review]

**Review by Tweak4141 — APPROVED** [review]

**Pull request merged**
