### PR TITLE
Create kareem-g.json

### PR DESCRIPTION
**Pull request by kareem-g**
please work 🗡️

### CODE REVIEW

**Comment by wclarkey** [comment]
Your JSON format is incorrect. 
image
https://docs.is-a-good.dev/format#json-format-template

**Comment by Tweak4141** [comment]
Still is not the correct format.
Please fix.

**Comment by Tweak4141** [comment]
Replace "record-type" with "CNAME"

**Comment by kareem-g** [comment]
Done! i hope it works now :D

**Pull request merged**
