### PR TITLE
Update nolimanom.json

### PR DESCRIPTION
**Pull request by nolimanom**
adding "A" record
(vercel also require it somewhy)

### CODE REVIEW

**Comment by Tweak4141** [comment]
You can only have an A record or CNAME. Additionally, name must match your file name for CNAME and A record types.

**Comment by nolimanom** [comment]
> You can only have an A record or CNAME. Additionally, name must match your file name for CNAME and A record types.

Hello, i've removed CNAME

**Comment by Tweak4141** [comment]
This is invalid, name must match the file name.

**Comment by nolimanom** [comment]
> This is invalid, name must match the file name.

fixed

**Comment by Tweak4141** [comment]
> > This is invalid, name must match the file name.
> 
> fixed

Still invalid. Please remove the is-a-good.dev part, you had it correct before.

**Comment by nolimanom** [comment]
> > > This is invalid, name must match the file name.
> > 
> > 
> > fixed
> 
> Still invalid. Please remove the is-a-good.dev part, you had it correct before.

done, sorry for wasting your time

**Comment by Tweak4141** [comment]
Name for vercel must just be _vercel

**Comment by nolimanom** [comment]
> Name for vercel must just be _vercel
done

**Review by Tweak4141 — APPROVED** [review]

**Pull request merged**
