### PR TITLE
Create nico.json

### PR DESCRIPTION
**Pull request by avalynndev**
This website it not for me, this is for Nicosnico.

### CODE REVIEW

**Comment by Tweak4141** [comment]
> Nicosnico

Does this user have a Github account? If they do, could you mention them in this thread, and ask them to verify that they want this subdomain? This will also allow for them to edit the file in the future.

**Comment by NicoGaming77** [comment]
Yes this is my domain

**Comment by avalynndev** [comment]
@Tweak4141 Pls don't rename the file to nico-ten.json
We want it to be Nico.json

**Comment by Tweak4141** [comment]
> @Tweak4141 Pls don't rename the file to nico-ten.json We want it to be Nico.json

The CNAME record you provided is `nico-ten`

**Comment by avalynndev** [comment]
That is cuz, we can't get the nico domain.. idk why

**Comment by Tweak4141** [comment]
> That is cuz, we can't get the nico domain.. idk why

What?
If the CNAME value is `nico-ten`, then the record will be created as `nico-ten`. As such the filename should match the CNAME value.

**Comment by avalynndev** [comment]
ok then :(

**Comment by Tweak4141** [comment]
You can take the subdomain `nico`, no one has taken it yet. I don't quite understand what the issue is here.

**Comment by NicoGaming77** [comment]
Yes, the subdomain should be nico.

**Pull request merged**
