### PR TITLE
Update anon.json

### PR DESCRIPTION
**Pull request by anondev-sudo**

### CODE REVIEW

**Comment by anondev-sudo** [comment]
Changing hosting + adding email forwarding

**Comment by Tweak4141** [comment]
Hi there @anondev-sudo , we do not accept MX records.

**Comment by anondev-sudo** [comment]
why

**Comment by anondev-sudo** [comment]
@Tweak4141 Merge it I removed MX

**Review by DEV-DIBSTER — APPROVED** [review]

**Pull request merged**
