### PR TITLE
Delete william.json

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**
Not gonna re-add it. I don't use it.

### CODE REVIEW

**Review by DIBSTERYT — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
@Tweak4141 why can't it be merged..? I kust want my subdomain deleted.

**Comment by Tweak4141** [comment]
> @Tweak4141 why can't it be merged..? I kust want my subdomain deleted.

I have already explained it.

**Comment by DIBSTERYT** [comment]
I think he forgot lol.

**Comment by WilliamDavidHarrison** [comment]
> I think he forgot lol.

It's in the Discord server.

**Comment by wclarkey** [comment]
Worth closing this and reopening once delete is implemented?

**Comment by Tweak4141** [comment]
@wclarkey I'll process deletes later today hopefully.

**Pull request merged**
