### PR TITLE
Claiming luca.is-a-good.dev

### PR DESCRIPTION
**Pull request by MrDaPoyo**
Someone claimed it, but he isn't using it and his email isn't working(I tried to contact him, but it showed some MX error).
I'm also called Luca and I would love to claim this lovely domain with my name.
Regards, Luca.

### CODE REVIEW

**Comment by Tweak4141** [comment]
@lucatolton
Please confirm you still are using this subdomain.

**Comment by Tweak4141** [comment]
@MrDaPoyo We won't transfer this subdomain until the owner confirms that they are fine with this. If you need a subdomain asap, I would come up with another subdomain.

**Comment by MrDaPoyo** [comment]
> @MrDaPoyo We won't transfer this subdomain until the owner confirms that they are fine with this. If you need a subdomain asap, I would come up with another subdomain.

Ok! Thanks, Tweak. I already tried to contact the owner, but his email forwarding service wasn't working.

**Comment by MrDaPoyo** [comment]
@Tweak4141 He isn't answering...

**Comment by Tweak4141** [comment]
@MrDaPoyo Please be patient, it has only been 3 days.
We do not transfer subdomains unless the owner has consented.

**Comment by lucatolton** [comment]
hey, sorry have been away for a while. i’m totally fine with someone else taking the domain as i’m not using it, and if i need one i can use a different sub. thanks!

**Comment by Tweak4141** [comment]
@lucatolton Thank you for the prompt response.

**Comment by MrDaPoyo** [comment]
> @MrDaPoyo There are some issues with your JSON. Instead of "github", your name should still be "luca". Please fix this, and I'll have it merged asap.

Of course!

**Review by MrDaPoyo — COMMENTED** [review]
Alright!

**Comment by MrDaPoyo** [comment]
@Tweak4141 It's corrected, can you merge it, please? And I also want to ask you, can I also claim poyo.is-a-good.dev? Thanks for your comprehension!

**Comment by Tweak4141** [comment]
@MrDaPoyo Unfortunately, we only offer one subdomain per person.

**Comment by MrDaPoyo** [comment]
@Tweak4141 Okay! Is it already merged? Thanks for your help!

**Pull request closed without merging**
