### PR TITLE
prettier + match new format

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**
Don't revert #190, I'll just continue it on this PR.

### CODE REVIEW

**Comment by wclarkey** [comment]
When ready, request reviews from me and tweak

**Comment by WilliamDavidHarrison** [comment]
Ok, I forgot about this PR lol
I'll finish it later today possibly

**Comment by WilliamDavidHarrison** [comment]
@wclarkey This is ready to merge. I also added #194 to resolve merge conflicts.

**Review by wclarkey — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
@wclarkey The txt files have <txtname>.<subdomain>

**Comment by Tweak4141** [comment]
> @wclarkey The txt file is for _tixte-challenge.kamino.is-a-good.dev not the root.

This isn't for the root, and was already preapproved before.

**Comment by WilliamDavidHarrison** [comment]
> > @wclarkey The txt file is for _tixte-challenge.kamino.is-a-good.dev not the root.
> 
> This isn't for the root, and was already preapproved before.

Yeah, but like wouldn't the name be _tixte-challenge.kamino

**Comment by wclarkey** [comment]
No.

> > > @wclarkey The txt file is for _tixte-challenge.kamino.is-a-good.dev not the root.
> > 
> > 
> > This isn't for the root, and was already preapproved before.
> 
> Yeah, but like wouldn't the name be _tixte-challenge.kamino

**Comment by WilliamDavidHarrison** [comment]
> No.
> 
> > > > @wclarkey The txt file is for _tixte-challenge.kamino.is-a-good.dev not the root.
> > > 
> > > 
> > > This isn't for the root, and was already preapproved before.
> > 
> > 
> > Yeah, but like wouldn't the name be _tixte-challenge.kamino

Oh

**Pull request merged**
