### PR TITLE
Domain purge

### PR DESCRIPTION
**Pull request by clarkedev**
Purge subdomain due to using Arc without prior permission.

### CODE REVIEW

**Comment by clarkedev** [comment]
@Tweak4141 Can you check over this please.

**Review by Tweak4141 — APPROVED** [review]

**Comment by clarkedev** [comment]
@Tweak4141 Is there a cache on domain deletion? https://anon.is-a-good.dev/ seems to still work.

**Comment by Tweak4141** [comment]
> @Tweak4141 Is there a cache on domain deletion? https://anon.is-a-good.dev/ seems to still work.

No, there shouldn't be.

**Comment by clarkedev** [comment]
> > @Tweak4141 Is there a cache on domain deletion? https://anon.is-a-good.dev/ seems to still work.
> 
> No, there shouldn't be.
It's gone now

**Pull request merged**
