### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**

### CODE REVIEW

**Comment by WilliamDavidHarrison** [comment]
is-a-good-dev/.github#2

**Comment by WilliamDavidHarrison** [comment]
> ## Validation Results
> Information Validation	Record Validation
> Valid information provided.	Valid records provided.
> ### JSON File Content
> ```json
> {"repo":"https://github.com/jian-css/jian.css","owner":{"username":"jian-css","email":"xyzscer@outlook.com"},"target":{"CNAME":{"name":"jian-css","value":"jian-css.gitbook.io"}},"proxied":false}
> ```

@Tweak4141 Uhh, I'm not updating any domains so I think this is a bug.

**Comment by WilliamDavidHarrison** [comment]
This is ready to merge.

**Comment by Tweak4141** [comment]
Will change the readme section on similar projects soon.

**Pull request closed without merging**
