### PR TITLE
fixing records for tixte and rebrandly

### PR DESCRIPTION
**Pull request by KaminoCodes**

### CODE REVIEW

**Comment by Tweak4141** [comment]
If we did allow nested subdomains, record would be created as `kamino.r.is-a-good.dev`

Nested subdomain support will be added later.

**Comment by KaminoCodes** [comment]
Could you please add the records stated in the json before this PR then? Currently kamino.i.is-a-good.dev points to tixte but doesn't respond and kamino.is-a-good.dev points to rebrandly

**Comment by wclarkey** [comment]
Either `kamino.i.is-a-good.dev` or `kamino.is-a-good.dev` will be deleted, please choose which one @KaminoCodes

**Comment by KaminoCodes** [comment]
kamino.i.is-a-good.dev

**Comment by wclarkey** [comment]
What would you like `kamino.is-a-good.dev` pointed to?

**Comment by KaminoCodes** [comment]
dns.tixte.com

**Comment by wclarkey** [comment]
Can you make any amends to the `json` file in `/sub-logs/` and create a pr if needed.

**Pull request closed without merging**
