### PR TITLE
Create lxance-hacker.json

### PR DESCRIPTION
**Pull request by LxaNce-Hacker**
how to host ?

### CODE REVIEW

**Comment by LxaNce-Hacker** [comment]
I've checked 
please allow to host my domain

**Comment by wclarkey** [comment]
Be patient

**Comment by wclarkey** [comment]
Be patient

**Comment by LxaNce-Hacker** [comment]
> You're just a few steps away from getting a new subdomain! Please double check that you have followed the format found [here](https://docs.is-a-good.dev/format). Once everything checks out, the maintainers will merge this PR and you should be good to go!

I've checked 
please continue process

**Comment by LxaNce-Hacker** [comment]
Sir,
how many time I wait ?

**Pull request merged**
