### PR TITLE
Create kawet.json

### PR DESCRIPTION
**Pull request by Kawet00**

### CODE REVIEW

**Review by WilliamDavidHarrison — APPROVED** [review]

**Comment by Kawet00** [comment]
@WilliamDavidHarrison a problem? with the checking?

**Comment by Tweak4141** [comment]
@Kawet00 You must provide an email to use this service.

**Review by Kawet00 — COMMENTED** [review]
I add an email

**Review by WilliamDavidHarrison — APPROVED** [review]

**Review by DEV-DIBSTER — APPROVED** [review]
Looks good, website is reachable as well.

**Pull request merged**
