### PR TITLE
Update and rename @.json to vulcan49343777.json

### PR DESCRIPTION
**Pull request by DoctorStrange49**

### CODE REVIEW

**Comment by wclarkey** [comment]
Why are your deleting `@.json`? @DoctorStrange49

**Comment by DoctorStrange49** [comment]
I haven't deleted i just renamed it as per written in readme

**Comment by wclarkey** [comment]
I'm not sure where that is written but you **do not** just rename and edit other records that are already there. You create a new file.

**Comment by Tweak4141** [comment]
> I haven't deleted i just renamed it as per written in readme

It doesn't say rename, it says create a new file. Please read the instructions again.

**Comment by DoctorStrange49** [comment]
vulcan49343777.json
Ohk is the file i created ok ?

**Comment by DoctorStrange49** [comment]
I'll add @.json to my fork repo from original one .

**Comment by Tweak4141** [comment]
> vulcan49343777.json Ohk is the file i created ok ?

No, you have an invalid CNAME Record.

**Comment by DoctorStrange49** [comment]
I didn't understood what do we have to write in CName Record i asked in issue section also

**Comment by Tweak4141** [comment]
> I didn't understood what do we have to write in CName Record i asked in issue section also
A cname record?

**Comment by wclarkey** [comment]
Always check if a project has docs before you submit a pr or create an /comment on an issue

**Comment by ElonMusk49** [comment]
How to get information about my subdomain?

**Comment by ElonMusk49** [comment]
Any control panel type thing ?

**Comment by wclarkey** [comment]
> How to get information about my subdomain?

https://github.com/is-a-good-dev/Register/issues/110

**Pull request merged**
