### PR TITLE
prettier + match new format

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**

### CODE REVIEW

**Comment by wclarkey** [comment]
The format is incorrect.

**Comment by wclarkey** [comment]
nevermind

**Review by wclarkey — APPROVED** [review]

**Review by Tweak4141 — APPROVED** [review]

**Comment by WilliamDavidHarrison** [comment]
@wclarkey @Tweak4141 this wasn't done but ok

**Comment by WilliamDavidHarrison** [comment]
That's why I marked it as a draft

**Comment by Tweak4141** [comment]
> @wclarkey @Tweak4141 this wasn't done but ok

Didn't see draft, must have missed it. My apologies.

**Comment by wclarkey** [comment]
I must have also missed that

**Pull request merged**
