### PR TITLE
Update eric.json

### PR DESCRIPTION
**Pull request by ericthomasca**
If this doesn't work, I'm going to stop trying lol

### CODE REVIEW

**Comment by wclarkey** [comment]
A `CNAME` pointing to the domain wont work as a redirect. Use a service such as [redirect pizza](https://redirect.pizza/)

**Comment by ericthomasca** [comment]
I think that is how you use redirect.pizza

**Comment by ericthomasca** [comment]
@wclarkey Can you update the records to repair this error

IPv6 (AAAA) record "2606:50c0:8000:0:0:0:0:153, 
                                 2606:50c0:8001:0:0:0:0:153, 
                                 2606:50c0:8002:0:0:0:0:153, 
                                 2606:50c0:8000:0:0:0:0:153" 
should be removed or changed to "2a12:5240::1"

**Comment by wclarkey** [comment]
hmm

**Comment by wclarkey** [comment]
Thats an issue with Redirect Pizza not us.

**Comment by ericthomasca** [comment]
Disregard. Everything works! Thanks!

**Pull request merged**
