### PR TITLE
Create gpchn.json

### PR DESCRIPTION
**Pull request by gpchn**
thank you for your efforts

Please feel free to contact me if there are any problems (although I may not come often)

### CODE REVIEW

**Review by KaminoCodes — DISMISSED** [review]

**Comment by Tweak4141** [comment]
Hey there @gpchn 
Did you want blog.gpchn.is-a-good.dev?

**Comment by Tweak4141** [comment]
Currently your chosen CNAME is not permitted, as it may associate your personal blog with is-a-good.dev

**Comment by gpchn** [comment]
Sorry, I think I made a mistake.
I haven't quite understood the document. So I opened another person's file casually, and I thought it was a description.
Thank you for being so responsible. Actually, I want 'gpchn.is-a-good.dev' redirect to 'gpchn.pages.dev'. How to write correctly? I'm sorry I'm so inexperienced.

**Comment by gpchn** [comment]
Besides, I have a private repo. Can I write this repo directly in the file so that I don't have to use a third-party website to redirect to the hosting website of that repo?
I'm not sure personal is feasible.

**Comment by Tweak4141** [comment]
What are you using to host your website?

**Comment by Tweak4141** [comment]
Ah, you are using CloudFlare pages. In that case, just put gpchn as name value, and value as gpchn.pages.dev

**Comment by Tweak4141** [comment]
Once this is merged, go to CloudFlare dashboard > pages > gpchn.pages.dev > custom domains and add gpchn.is-a-good.dev.

**Comment by gpchn** [comment]
Thank you very much! I'll try it now.
By the way, it's very late in the morning in my area. I have to go to bed after this.

**Comment by gpchn** [comment]
I think so. It seems to be done.

**Review by Tweak4141 — APPROVED** [review]

**Pull request merged**
