### PR TITLE
add invalid domain check + cleanup

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**

### CODE REVIEW

**Comment by Tweak4141** [comment]
Please, don't change the existing format of the code.

**Comment by WilliamDavidHarrison** [comment]
> Please, don't change the existing format of the code.

What do mean exactly? Like using `"` instead of `'`?

**Comment by Tweak4141** [comment]
> > Please, don't change the existing format of the code.
> 
> What do mean exactly? Like using `"` instead of `'`?

Yes, and also the if () spacing.

**Comment by WilliamDavidHarrison** [comment]
> Yes, and also the if () spacing.

Fixed ce91b937454c0f04030b292dd5c16f88f7e5ccaf

**Pull request merged**
