### PR TITLE
Register nolimanom.is-a-good.dev

### PR DESCRIPTION
**Pull request by nolimanom**
Added `nolimanom.is-a-good.dev` using the [CLI](https://www.npmjs.com/package/@is-a-good-dev/cli).

### CODE REVIEW

**Review by Tweak4141 — CHANGES_REQUESTED** [review]
Invalid A record value.

**Comment by nolimanom** [comment]
> Invalid A record value.

fixed

**Comment by nolimanom** [comment]
> CNAME values cannot be in an array.

fixed, sorry i'm kinda stupid

**Review by Tweak4141 — APPROVED** [review]

**Comment by Tweak4141** [comment]
No worries.

**Comment by nolimanom** [comment]
@Tweak4141 just need some help, when i'm opening this url show's that "domain doesn't exist"

**Comment by nolimanom** [comment]
@Tweak4141 can you change cname to https://nolimanom.serv00.net/index.html 😅

**Comment by Tweak4141** [comment]
> @Tweak4141 just need some help, when i'm opening this url show's that "domain doesn't exist"

This is an issue with your provider. We cannot fix this on our end.

**Comment by Tweak4141** [comment]
> @Tweak4141 can you change cname to https://nolimanom.serv00.net/index.html 😅

This is an invalid value.

**Comment by nolimanom** [comment]
> > @Tweak4141 can you change cname to https://nolimanom.serv00.net/index.html 😅
> 
> This is an invalid value.

change to "nolimanom.vercel.app" then

**Comment by Tweak4141** [comment]
> > > @Tweak4141 can you change cname to https://nolimanom.serv00.net/index.html 😅
> > 
> > 
> > This is an invalid value.
> 
> change to "nolimanom.vercel.app" then, and sorry for the time you've wasted on me

Please create a new pull request with the desired changes, any manual corrections will be overwritten by the system with whatever value is in your file.

**Pull request merged**
