### PR TITLE
dhyan99

### PR DESCRIPTION
**Pull request by D99-1**

### CODE REVIEW

**Comment by Tweak4141** [comment]
@D99-1 Please fix name, it should be what you want your subdomain to be.

**Comment by D99-1** [comment]
@Tweak4141 the pull req name?

**Comment by D99-1** [comment]
If not then just lmk

**Comment by wclarkey** [comment]
The `"name"` should be changed to what you want the subdomain to be. 
```json
  "target": {
    "CNAME": {
      "name": "portfolio site", 
      "value": "d99-1.github.io"
    }
  },
```
@D99-1

**Comment by D99-1** [comment]
@wclarkey @Tweak4141 should be good noe

**Comment by Tweak4141** [comment]
PR has moved to #224, not sure why check is failing.

**Pull request closed without merging**
