### PR TITLE
Register parad1se.is-a-good.dev

### PR DESCRIPTION
**Pull request by Parad1se-py**
Added `parad1se.is-a-good.dev` using the [CLI](https://www.npmjs.com/package/@is-a-good-dev/cli).

### CODE REVIEW

**Comment by Parad1se-py** [comment]
Yo! I'll add the website code later.
Thanks!

**Comment by Tweak4141** [comment]
Your JSON file is invalid.

**Comment by Parad1se-py** [comment]
Alright, I'm new to this.
What do I need to do in order to fix this? The documentation wasn't really clear enough for me

**Comment by Tweak4141** [comment]
https://is-a-good-dev.github.io/docs/format.html

Follow the format.

**Comment by Parad1se-py** [comment]
I did, I pasted all that code in the CLI registration.

**Comment by Parad1se-py** [comment]
Alright, please check it now.

**Review by Tweak4141 — APPROVED** [review]

**Pull request merged**
