### PR TITLE
added improvmx

### PR DESCRIPTION
**Pull request by boolean44-repos**

### CODE REVIEW

**Comment by wclarkey** [comment]
Those have been added. Add a comment below if there is any issues with the priority on the MX records.

**Comment by wclarkey** [comment]
Can you email me via will@wclarke.dev and send any relevent screen shots?

**Comment by boolean44-repos** [comment]
done

**Comment by boolean44-repos** [comment]
mx 1 needs priority 10 and mx 2 needs priority 20

**Comment by wclarkey** [comment]
Added

**Comment by boolean44-repos** [comment]
still not working, should i try mail.crisisbot.is-a-good.dev?

**Pull request merged**
